version: 2
jobs:
  build:
    working_directory: /gatling
    docker:
      - image: docker:18.06.2-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Gatling Docker image
          command: |
            docker build --cache-from=gatling -t gatling .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/gatling.tar gatling
      - save_cache:
          key: v1-{{ .Branch }}-{{ .Environment.CIRCLE_WORKFLOW_ID }}
          paths:
            - /caches/gatling.tar
  test:
    working_directory: /gatling
    docker:
      - image: docker:18.06.2-ce-git
    steps:
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-{{ .Branch }}-{{ .Environment.CIRCLE_WORKFLOW_ID }}
          paths:
            - /caches/gatling.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/gatling.tar | true
      - run:
          name: Run Gatling Docker image
          command: |
            set +o pipefail
            docker run -it gatling --help | grep -iq "/opt/gatling" | true
workflows:
  version: 2
  build:
    jobs:
      - build
      - test:
          requires:
            - build
